public class FatApexClass {
    public void main() {
        String message = 'Hello, world!';
    }

    public void GeneratedMethod1() {
        Integer methodInt = 1;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }

    public void GeneratedMethod2() {
        Integer methodInt = 2;
        String message = '';
        
        if (methodInt == 13) {
            message = 'This is a pretty unlucky method';
        } else {
            message = 'This method should be good';
        }
    }
    public void BottomAnchorMethod() {
        String message = 'I\'m just here to create diff regions above me';
    }
}